### ISSUE TITLE
Custom input for demo

### ISSUE THREAD

**Issue by lahirimahasaya** [walsvid/Pixel2MeshPlusPlus#17]
for giving the custom input for demo what is the cameras.txt means and can you please explain whether those are bounding box values and class or something else

**Comment by walsvid** [comment]
The meaning of each lines in file rendering_metadata.txt: from the left, they are azimuth, elevation, in-plane rotation, distance, the field of view. https://en.wikipedia.org/wiki/Horizontal_coordinate_system

**Comment by quintendewilde** [comment]
which program do you use to get that data in the same way the cameras.txt uses it.
(if the image is abstracted from a jpeg and not from an already 3D drawing (the plane)) 

Kind regards, 

Love the project!

**Comment by walsvid** [comment]
> which program do you use to get that data in the same way the cameras.txt uses it.
> (if the image is abstracted from a jpeg and not from an already 3D drawing (the plane))
> 
> Kind regards,
> 
> Love the project!

Hi @quintendewilde , for the general photos taken, the key input here is the camera extrinsics, specifically the rotation matrix and the translation vector of the camera. The format cameras.txt is not mandatory, as we can see from our code that the most critical parameters are the camera rotation and translation, while some other data are not used. It may be necessary to obtain these parameters with the help of the camera pose estimation method.

**Comment by topinfrassi01** [comment]
@walsvid Sorry to come back to thi issue, but I do have a question regarding the camera poses and I can't seem to figure out an answer.

I'd like to know to what "origin" are these camera extrinsics refering to? For example, if I was to have extrinsics of 0 rotation, 0 translation, from where would I see the object and how is this dealt with when the mesh is first generated in the coarse shape generation?

I hope my question is clear, otherwise I will develop it more. Thank you a lot for your time.

**Comment by walsvid** [comment]
Hi @topinfrassi01 , we assume the 0 rotation is the canonical view of the origin mesh in ShapeNet dataset, e.g. car head towards the camera. 0 translation will put the camera at the center of the world coordinates. 

The RT mentioned above is an absolute value. Since we choose one of the images as the reference image, the effective code is relative RT. For convenience, I think you can choose the extrinsics of one of the images as 0.

**Comment by topinfrassi01** [comment]
@walsvid  So if I understand correctly, the extrinsic parameters are relative to an arbitrary pose and it should work as long as the relative rotation/translation are always coherent regarding this arbitrary pose?

**Comment by walsvid** [comment]
@topinfrassi01 Yes, your understanding is correct.
