### ISSUE TITLE
About the input shape of the model

### ISSUE THREAD

**Issue by deephog** [walsvid/Pixel2MeshPlusPlus#23]
Thank you for sharing this amazing work!

One question I wanted to ask is that I see you used the "batch" dimension of the input to wrap the multi-view input images, which means this model can never really be used with a batch size larger than 1 right? 

Thanks!

**Comment by topinfrassi01** [comment]
Indeed the code wasn't written to be used with a higher batch size than one. 

I tried to modify it (I'm not one of the author of the Git, but I've used the architecture extensively over the last months) but it would be pretty complicated. 

Considering that not all GT models have the same number of vertices, there's already a first problem since the dimension of the GT wouldn't be constant over a batch.

**Comment by deephog** [comment]
> Indeed the code wasn't written to be used with a higher batch size than one.
> 
> I tried to modify it (I'm not one of the author of the Git, but I've used the architecture extensively over the last months) but it would be pretty complicated.
> 
> Considering that not all GT models have the same number of vertices, there's already a first problem since the dimension of the GT wouldn't be constant over a batch.

Thank you for the answer. I'm curious though, if you are talking about other GNN models that take meshes of different shapes as input, yes I agree with you that multi-batch is difficult. But this model always starts with the same ellipse right? And then you deform it into various shapes.

And now actually I think using the batch dimension to wrap the multi-view images is a great idea, so Tensorflow will take care of the parallelism of the encoding process of the image features.

**Comment by topinfrassi01** [comment]
Yeah the prediction will always have the same number of vertices, but the ground truths won't, so what would the batch of ground truth look like? 

If for example I have a batch where the expected models have 1000, 1500 and 2000 vertices, what will the ground truth batch dimension be?

**Comment by deephog** [comment]
> Yeah the prediction will always have the same number of vertices, but the ground truths won't, so what would the batch of ground truth look like?
> 
> If for example I have a batch where the expected models have 1000, 1500 and 2000 vertices, what will the ground truth batch dimension be?

You are right......

BTW, I have another question about this model. I realized that the hypothesis sampling module is basically just extending each vertex to its 42 neighbors and then choosing one of them as its next destination. However, that icosahedron is preset, with a fixed dimension, which means with two deformation reasoning modules, the deformation can be no further than 2 x that_fixed_length. And also, I found that fixed length...is quite small, like 0.015 something, and it is universal, so no matter you are deforming a chair or a plane, you are dealing with the same range of misalignment, which is very curious to me.

Or, maybe the ShapeNet models are pre-normalized into a dimensionless state, so the physical size of the models no longer matter? Do you have any idea about this? Thanks!

**Comment by deephog** [comment]
> Yeah the prediction will always have the same number of vertices, but the ground truths won't, so what would the batch of ground truth look like?
> 
> If for example I have a batch where the expected models have 1000, 1500 and 2000 vertices, what will the ground truth batch dimension be?

I found it, paper that describes ShapeNet said the models are normalized. The equation is like (V - Centroid)/Diagonal , that means the normalized locations can be negative? How well is the model with all "relu" activation functions handle negative outputs?

**Comment by topinfrassi01** [comment]
Okay so about your first question, yes the deformation cannot be higher than 2 x that_fixed_length. However you can adapt that length to whatever you want. Since the icosahedron is centered on zero, you can make it bigger or smaller at your convenience using this line of code : `data["sample_coord"] = data["sample_coord"] * SOME_SCALE_FACTOR). 

With normalized models, this gives you the possibility to make quite big deformations. 

Now, regarding the negative vertices locations, `relu` doesn't matter much because if you look at the `DeformationReasoning` module, you compute a probability density on each directions using a sigmoid activation function, you multiply this probability density by the directions and then you add this deformation to the existing points.

Considering relu is used only when computing the scores, it doesn't matter much if some coordinates are negative or positive. Hope this answers your questions.
